version: 0.1
os: linux
files:
  - source: /
    destination: /home/ubuntu/petscube/petscube
hooks:  
  ApplicationStart:
    - location: Scripts/start_server.sh
      timeout: 3600
  ApplicationStop:
    - location: Scripts/stop_server.sh
      timeout: 3600     
artifacts:
  files:
    - '**/*'
    name: s3-to-s3-latest-build.zip      