version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/petscube/petscube
hooks:  
  ApplicationStart:
    - location: Scripts/start_server.sh
      timeout: 3600
  ApplicationStop:
    - location: Scripts/stop_server.sh
      timeout: 3600     
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)    