/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const appconfig = {
    "endpoint_url": "ap-south-1",
    
};


export default appconfig;
